config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy'

  namespace :admin do
    resources :users
    resources :questions
  end

  resources :questions do
    resources :answers, only: [:create]
  end

  get 'answers/create'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :body, presence: true, length: { maximum: 1000 }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 1000 }
  has_many :answers, dependent: :destroy

  # 以下検索条件を絞るための実装。これでtitle,body以外を検索できないようになる。
  def self.ransackable_attributes(auth_object = nil)
    %w[title body]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
            uniqueness: { case_sensitive: false }

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  scope :related_to_question, ->(question) { joins(:answers).where(answers: { question_id: question.id }) }

  def mine?(object)
    object.user_id == id
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :require_admin
  def index
    questions = Question.includes(:user)
    if params[:resolved_status] == 'false'
      questions = questions.where(resolved_status: false)
    elsif params[:resolved_status] == 'true'
      questions = questions.where(resolved_status: true)
    end
    @q = questions.ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new(question_id: @question.id)
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy!
    redirect_to admin_questions_url, notice: "質問「#{question.title}」を削除しました。"
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy!
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image, :admin, :password, :password_confirmation)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    #@question = Question.find(params[:question_id])
    @answer = current_user.answers.build(answer_params.merge(question_id: params[:question_id]))
    if @answer.save
      #自分の回答でなければ「質問に回答がありました」と届く。
      unless current_user.mine?(@answer.question)
        QuestionMailer.with(user: @answer.question.user, question: @answer.question).answer_created.deliver_now
      end
      #回答したことがあれば？「あなたが回答したことのある質問に新しい回答がつきました」と届く。
      User.related_to_question(@answer.question).distinct.each do |user|
        next if user.id == current_user.id || user.mine?(@answer.question)
        AnswerMailer.with(user: user, question: @answer.question).answer_created.deliver_now
      end
      redirect_to question_url(params[:question_id]), notice: "質問に回答しました。"
    else
      flash[:notice] = '失敗しました'
      render :'questions/show'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url, notice: "ログインしてください。" unless current_user
  end

  def require_admin
    redirect_to root_url, notice: "権限がありません。" unless current_user.admin?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    questions = Question.includes(:user)
    if params[:resolved_status] == 'false'
      questions = questions.where(resolved_status: false)
    elsif params[:resolved_status] == 'true'
      questions = questions.where(resolved_status: true)
    end
    @q = questions.ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new(question_id: @question.id)
    @answers = @question.answers.includes(:user)
  end

  def new
    @question = Question.new
  end

  def edit
    @question = current_user.questions.find(params[:id])
  end

  def update
    @question = current_user.questions.find(params[:id])

    if @question.update(question_params)
      redirect_to @question, notice: "質問「#{@question.title}」を更新しました。"
    else
      flash[:notice] = '失敗しました'
      render :edit
    end
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      User.where.not(id: current_user.id).each do |user|
        QuestionMailer.with(user: user, question: @question).creation_email.deliver_now
      end
      redirect_to @question, notice: "質問「#{@question.title}」を投稿しました。"
    else
      flash[:notice] = '失敗しました'
      render :new
    end
  end

  def destroy
    question = current_user.questions.find(params[:id])
    question.destroy!
    redirect_to questions_url, notice: "質問「#{question.title}」を削除しました。"
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :resolved_status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました。'
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      flash[:notice] = '失敗しました'
      render :new
    end
  end

  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to root_url, notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    current_user.destroy!
    redirect_to root_url, notice: "ユーザー「#{current_user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image, :admin, :password, :password_confirmation)
  end

end

app/views/admin/questions/index.html.slim
h1 Admin::Questions#index

.mb-5
  = link_to '全て', questions_path, class: "#{ params[:resolved_status].nil? ? 'btn btn-success' : 'btn btn-outline-success' }"
  = link_to '未解決',  questions_path(resolved_status: false) , class: "#{ params[:resolved_status] == "false" ? 'btn btn-success' : 'btn btn-outline-success' }"
  = link_to '解決済み',  questions_path(resolved_status: true) , class: "#{ params[:resolved_status] == "true" ? 'btn btn-success' : 'btn btn-outline-success' }"


= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    .col-sm-6
      = f.search_field :title_cont, class: 'form-control'
    .col-sm-6
      = f.submit class: 'btn btn-outline-primary'

= link_to '新規投稿', new_question_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= "投稿者"
      th= "質問タイトル"
      th= "ステータス"
      th
  tbody
    - @questions.each do |question|
      tr
        td= question.user.name
        td= link_to question.title, admin_question_path(question)
        - if question.resolved_status == true
          td= "解決済み"
        - elsif question.resolved_status == false
          td= "未解決"
        td
          = link_to '削除', [:admin, question], method: :delete, data: { confirm: "質問「#{question.title}」を削除しますか？"}, class: 'btn btn-danger'
.mb-3
  = paginate @questions
  = page_entries_info @questions

app/views/admin/questions/show.html.slim
h1 Admin::Questions#show

table.table.table-hover
  tbody
    tr
      td= @question.user.name
      td= @question.title
      td= simple_format(h(@question.body),{}, sanitize: false, wrapper_tag: "div")
      td= link_to '削除', @questions, method: :delete, data: { confirm: "質問「#{@question.title}」を削除しますか？"}, class: 'btn btn-danger'
      td= @question.resolved_status ? '解決済み':'受付中'
    tr
      td
        = form_with model: [@question, @answer], local: true do |f|
          .form-group
            = f.label :body
            = f.text_area :body, class: 'form-control', id: 'question_answer'
          = f.submit '回答する', class: 'btn btn-primary'
    tr
      td
        - @question.answers.each do |answer|
          tr
            td= answer.user.name
            td= answer.body

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message


= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :image, 'アバター画像'
    = f.file_field :image, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label'
    = f.check_box :admin, class: 'form-check-input'
    | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 Admin::Users#edit
.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 Admin::Users#index
= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:image)
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:admin)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td= image_tag user.image, class: "rounded-circle", size: "45x45" if user.image.attached?
        td= link_to user.name, [:admin, user]
        td= user.email
        td= user.admin? ? 'あり' : 'なし'
        td= user.created_at
        td= user.updated_at
        td
          = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
          = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 Admin::Users#new
.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 Admin::Users#show

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:image)
      td= image_tag @user.image, class: "rounded-circle", size: "150x150" if @user.image.attached?
    tr
      th= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "タスク「#{@user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Qanda
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Qanda
      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item= link_to '質問一覧', questions_path, class: 'nav-link'
          li.nav-item= link_to 'ユーザー一覧', users_path, class: 'nav-link'
          - if current_user.admin?
            li.nav-item= link_to '管理者：新規管理者登録', new_admin_user_path, class: 'nav-link'
            li.nav-item= link_to '管理者：質問一覧', admin_questions_path, class: 'nav-link'
            li.nav-item= link_to '管理者：ユーザー一覧', admin_users_path, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', login_path, method: :delete, class: 'nav-link'
          li =image_tag current_user.image, class: "rounded-circle", size: "40x40" if current_user.image.attached?
          li.nav-item= link_to current_user.name, user_path(current_user), class: 'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
          li.nav-item= link_to '新規登録', new_user_path, class: 'nav-link'


    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield

app/views/questions/_form.html.slim
- if question.errors.present?
  ul#error_explanation
    - question.errors.full_messages.each do |message|
      li= message

= form_with model: question, local: true do |f| #@を外してquestionに変える
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'question_title'
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control', id: 'question_body'
  = f.submit '投稿', class: 'btn btn-primary'

app/views/questions/edit.html.slim
h1 Questions#edit
= render partial: 'form', locals: { question: @question }

app/views/questions/index.html.slim
h1 Questions#index

.mb-5
  = link_to '全て', questions_path, class: "#{ params[:resolved_status].nil? ? 'btn btn-success' : 'btn btn-outline-success' }"
  = link_to '未解決',  questions_path(resolved_status: false) , class: "#{ params[:resolved_status] == "false" ? 'btn btn-success' : 'btn btn-outline-success' }"
  = link_to '解決済み',  questions_path(resolved_status: true) , class: "#{ params[:resolved_status] == "true" ? 'btn btn-success' : 'btn btn-outline-success' }"

= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    .col-sm-6
      = f.search_field :title_cont, class: 'form-control'
    .col-sm-6
      = f.submit class: 'btn btn-outline-primary'

= link_to '新規投稿', new_question_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= "投稿者"
      th= "質問タイトル"
      th= "ステータス"
      th
  tbody
    - @questions.each do |question|
      tr
        td= question.user.name
        td= link_to question.title, question
        - if question.resolved_status == true
          td= "解決済み"
        - elsif question.resolved_status == false
          td= "未解決"
        - if question.user.id == current_user.id
          td
            = link_to "編集", edit_question_path(question), class: "btn btn-primary mr-3"
            = link_to '削除', question, method: :delete, data: { confirm: "質問「#{question.title}」を削除しますか？"}, class: 'btn btn-danger'
        - else
          td


.mb-3
  = paginate @questions
  = page_entries_info @questions

app/views/questions/new.html.slim
h1 Questions#new

= render partial: 'form', locals: { question: @question }

app/views/questions/show.html.slim
h1 Questions#show

table.table.table-hover
  tbody
    tr
      th="質問者"
      th="質問タイトル"
      th="質問内容"
      th="質問ステータス"
      th
    tr
      td= @question.user.name
      td= @question.title
      td= simple_format(h(@question.body),{}, sanitize: false, wrapper_tag: "div")
      td= @question.resolved_status ? '解決済み':'受付中'
      - if @question.user.id == current_user.id
        td
          = link_to '編集',  edit_question_path(@question), class: "btn btn-primary mr-3"
          = link_to '削除', @questions, method: :delete, data: { confirm: "質問「#{@question.title}」を削除しますか？"}, class: 'btn btn-danger'
          - if @question.resolved_status == false
            = link_to "解決済みにする", question_path(@question, params: { question: {resolved_status: true} }), method: :put, data: { confirm: "「#{@question.title}を解決済みにします。よろしいですか？」" }, class: "btn btn-success"
    tr
      td
      td= form_with model: [@question, @answer], local: true do |f|
          .form-group
            = f.text_area :body, class: 'form-control', id: 'question_answer'
          = f.submit '回答する', class: 'btn btn-primary'
      td
      td
      td
    tr
      th= ""
      th= "回答者"
      th= "回答"
      th= ""
      th= ""
    - @answers.each do |answer|
      tr
         td
         td= answer.user.name
         td= answer.body
         td
         td

app/views/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message


= form_with model: user, local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :image, 'アバター画像'
    = f.file_field :image, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/users/edit.html.slim
h1 Users#edit
.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/users/index.html.slim
h1 Users#index

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:image)
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td= image_tag user.image, class: "rounded-circle", size: "45x45" if user.image.attached?
        td= link_to user.name, user
        td= user.email
        td= user.created_at
        td= user.updated_at
        - if user.id == current_user.id
          td
            = link_to '編集', edit_user_path(user), class: 'btn btn-primary mr-3'
            = link_to '削除', user, method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'
        - else
          td

app/views/users/new.html.slim
h1 Users#new
.nav.justify-content-end


= render partial: 'form', locals: { user: @user }

app/views/users/show.html.slim
h1 Users#show

.nav.justify-content-end
  = link_to '一覧', users_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:image)
      td= image_tag @user.image, class: "rounded-circle", size: "150x150" if @user.image.attached?
    tr
      th= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at
- if current_user.id == @user.id
  = link_to '編集', edit_user_path(@user), class: 'btn btn-primary mr-3'
  = link_to '削除', @user, method: :delete, data: { confirm: "タスク「#{@user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'